import{a as w,S,i as a}from"./assets/vendor-DvfmeZXB.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&i(d)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const R="53393069-83cee6561783600a5d025c02b",A="https://pixabay.com/api/",f=15;async function y(r,o=1){try{const e={key:R,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:f,page:o};return(await w.get(A,{params:e})).data}catch(e){throw console.error("Error fetching:",e),e}}const h=document.querySelector(".gallery"),p=document.querySelector(".js-loader"),m=document.querySelector(".js-load-more"),q=new S(".gallery a",{captionsData:"alt",captionDelay:250});function g(r){if(!Array.isArray(r)||r.length===0)return;const o=r.map(e=>`
      <li class="gallery-item">
        <a href="${e.largeImageURL}" class="gallery-link">
          <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" class="gallery-image" />
        </a>
        <div class="info">
          <div class="info-item"><b>Likes</b><span>${e.likes}</span></div>
          <div class="info-item"><b>Views</b><span>${e.views}</span></div>
          <div class="info-item"><b>Comments</b><span>${e.comments}</span></div>
          <div class="info-item"><b>Downloads</b><span>${e.downloads}</span></div>
        </div>
      </li>`).join("");h.insertAdjacentHTML("beforeend",o),q.refresh()}function E(){h.innerHTML=""}function b(){p.classList.add("is-visible")}function v(){p.classList.remove("is-visible")}function L(){m.classList.add("is-visible")}function l(){m.classList.remove("is-visible")}const P=document.querySelector(".form"),B=document.querySelector(".js-load-more");let u="",n=1,c=0;P.addEventListener("submit",M);B.addEventListener("click",$);async function M(r){r.preventDefault();const o=r.target.elements["search-text"].value.trim();if(!o){a.error({message:"Please enter a search word",position:"topRight"});return}u=o,n=1,c=0,E(),l(),b();try{const e=await y(u,n),i=Array.isArray(e.hits)?e.hits:[];if(c=e.totalHits||0,i.length===0){a.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(i),n*f<c?L():(l(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{a.error({message:"Something went wrong. Try again later!",position:"topRight"})}finally{v()}}async function $(){n+=1,b();try{const r=await y(u,n),o=Array.isArray(r.hits)?r.hits:[];if(c=r.totalHits||c,o.length===0){l(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}g(o);const e=document.querySelector(".gallery-item");if(e){const{height:i}=e.getBoundingClientRect();window.scrollBy({top:i*2,behavior:"smooth"})}n*f>=c?(l(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):L()}catch{a.error({message:"Failed to load more images. Try again later.",position:"topRight"})}finally{v()}}
//# sourceMappingURL=index.js.map
